# Generated by Django 3.1 on 2020-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('query', models.CharField(max_length=1000)),
            ],
        ),
    ]
