# Generated by Django 3.1 on 2020-09-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
